name: Test

on:
  push:
    branches-ignore:
      - staging.*
      - production.*
env:
  GATSBY_CPU_COUNT: 2
  GATSBY_ENV: staging

jobs:
  lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      env:
          cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
    - run: npm ci --ignore-scripts
    - run: npm run build --if-present
    - run: npm test




