name: Lint

on:
  push:
    branches-ignore:
      - staging.*
      - production.*
env:
  GATSBY_CPU_COUNT: 2
  GATSBY_ENV: staging

jobs:
  lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      env:
          cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    - run: npm run build
    - run: npm test




