name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      GATSBY_CPU_COUNT: 2
      GATSBY_ENV: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: test
        run: |
          ls -lha
          pwd
          

